name: Build Assets

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'
      - 'dist/**'

jobs:
  build-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: npm install
      - run: npm run prod
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] Build assets"
          file_pattern: 'dist/*'
